# Generated by Django 5.1.6 on 2025-05-05 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='users.business'),
        ),
        migrations.AddField(
            model_name='partycategory',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='users.business'),
        ),
        migrations.AddField(
            model_name='party',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parties.partycategory'),
        ),
        migrations.AlterUniqueTogether(
            name='partycategory',
            unique_together={('business', 'name')},
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(fields=('business', 'party_name'), name='unique_party_per_business'),
        ),
    ]
