# Generated by Django 5.1.6 on 2025-05-05 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audittrail',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.business'),
        ),
        migrations.AddField(
            model_name='audittrail',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capitalentry',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.business'),
        ),
        migrations.AddField(
            model_name='currentassetentry',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.business'),
        ),
        migrations.AddField(
            model_name='currentliabilityentry',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.business'),
        ),
        migrations.AddField(
            model_name='fixedassetentry',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.business'),
        ),
        migrations.AddField(
            model_name='investmententry',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.business'),
        ),
        migrations.AddField(
            model_name='loanentry',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.business'),
        ),
        migrations.AddField(
            model_name='loansadvanceentry',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.business'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['business', 'date'], name='reports_aud_busines_3894ba_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['business', 'model_name', 'record_id'], name='reports_aud_busines_1b5fc7_idx'),
        ),
    ]
