# Generated by Django 5.1.6 on 2025-05-05 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('godown', '0002_initial'),
        ('inventory', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='users.business'),
        ),
        migrations.AddField(
            model_name='item',
            name='godown',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='godown.godown'),
        ),
        migrations.AddField(
            model_name='item',
            name='gstTaxRate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.gsttaxrate'),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_categories', to='users.business'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.itemcategory'),
        ),
        migrations.AddField(
            model_name='item',
            name='measuringUnit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.measuringunit'),
        ),
        migrations.AddField(
            model_name='service',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='users.business'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.itemcategory'),
        ),
        migrations.AddField(
            model_name='service',
            name='gstTaxRate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.gsttaxrate'),
        ),
        migrations.AddField(
            model_name='service',
            name='measuringUnit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.measuringunit'),
        ),
        migrations.AlterUniqueTogether(
            name='itemcategory',
            unique_together={('business', 'name')},
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('business', 'itemCode'), name='unique_itemcode_per_business'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('business', 'serviceCode'), name='unique_servicecode_per_business'),
        ),
    ]
