# Generated by Django 5.1.6 on 2025-05-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_no', models.CharField(max_length=50)),
                ('original_invoice_no', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField()),
                ('expense_with_gst', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card', 'Card'), ('Netbanking', 'Netbanking'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque')], default='Cash', max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount in %', max_digits=5)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount in percentage.', max_digits=5)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(max_length=255)),
                ('serviceType', models.CharField(choices=[('Service', 'Service')], default='Service', max_length=10)),
                ('purchasePrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('purchasePriceType', models.CharField(choices=[('With Tax', 'With Tax'), ('Without Tax', 'Without Tax')], default='With Tax', max_length=50)),
                ('ITC', models.CharField(choices=[('Eligible', 'Eligible'), ('Ineligible', 'Ineligible'), ('Ineligible Others', 'Ineligible Others')], default='Eligible', max_length=50)),
                ('sacCode', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=255)),
                ('itemType', models.CharField(choices=[('Product', 'Product')], default='Product', max_length=10)),
                ('purchasePrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('purchasePriceType', models.CharField(choices=[('With Tax', 'With Tax'), ('Without Tax', 'Without Tax')], default='With Tax', max_length=50)),
                ('ITC', models.CharField(choices=[('Eligible', 'Eligible'), ('Ineligible', 'Ineligible'), ('Ineligible Others', 'Ineligible Others')], default='Eligible', max_length=50)),
                ('hsnCode', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
