# Generated by Django 5.1.6 on 2025-05-05 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
        ('inventory', '0001_initial'),
        ('parties', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='users.business'),
        ),
        migrations.AddField(
            model_name='expense',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parties.party'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses_categories', to='users.business'),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.expensecategory'),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_items', to='expenses.expense'),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='gstTaxRate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.gsttaxrate'),
        ),
        migrations.AddField(
            model_name='expenseservice',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses_service', to='users.business'),
        ),
        migrations.AddField(
            model_name='expenseservice',
            name='gstTaxRate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_gsttaxrate', to='inventory.gsttaxrate'),
        ),
        migrations.AddField(
            model_name='expenseservice',
            name='measuringUnit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_measuringuunit', to='inventory.measuringunit'),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.expenseservice'),
        ),
        migrations.AddField(
            model_name='item',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_items', to='users.business'),
        ),
        migrations.AddField(
            model_name='item',
            name='gstTaxRate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_gsttaxrate', to='inventory.gsttaxrate'),
        ),
        migrations.AddField(
            model_name='item',
            name='measuringUnit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_measuringuunit', to='inventory.measuringunit'),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.item'),
        ),
        migrations.AlterUniqueTogether(
            name='expensecategory',
            unique_together={('business', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='expense',
            unique_together={('business', 'expense_no')},
        ),
        migrations.AddConstraint(
            model_name='expenseservice',
            constraint=models.UniqueConstraint(fields=('business', 'serviceName'), name='unique_serviceName_per_business'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('business', 'itemName'), name='unique_itemName_per_business'),
        ),
    ]
