# Generated by Django 5.1.6 on 2025-05-05 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cash_and_bank', '0001_initial'),
        ('purchase', '0001_initial'),
        ('sales', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='users.business'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='cash_and_bank.bankaccount'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.business'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='credit_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='sales.creditnote'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='debit_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='purchase.debitnote'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='sales.invoice'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='payment_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='sales.paymentin'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='payment_out',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='purchase.paymentout'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='purchase.purchase'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='purchase_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='purchase.purchasereturn'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='sales_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='sales.salesreturn'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['business', 'account'], name='cash_and_ba_busines_26155b_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['transaction_type'], name='cash_and_ba_transac_bdd697_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['date'], name='cash_and_ba_date_ffda6e_idx'),
        ),
    ]
