from django.core.management.base import BaseCommand
from inventory.models import MeasuringUnit

class Command(BaseCommand):
    help = 'Seed default measuring unit entries'

    def handle(self, *args, **kwargs):
        default_measuring_units = [
            {"name": "Aaaaaaaaaaa(G NEX)"},
            {"name": "Aana(ANA)"},
            {"name": "Acre(AC)"},
            {"name": "Ampoule(AMP)"},
            {"name": "Bags(BAG)"},
            {"name": "Bale(BAL)"},
            {"name": "Balls(BALL)"},
            {"name": "Barni(BAR)"},
            {"name": "Billions Of Units(BOU)"},
            {"name": "Blister(BLISTER)"},
            {"name": "Bolus(BOLUS)"},
            {"name": "Book(BK)"},
            {"name": "Bora(BOR)"},
            {"name": "Bottles(BTL)"},
            {"name": "Box(BOX)"},
            {"name": "Brass(BRASS)"},
            {"name": "Brick(BRICK)"},
            {"name": "Buckets(BCK)"},
            {"name": "Buckles(BKL)"},
            {"name": "Bunches(BUN)"},
            {"name": "Bundles(BDL)"},
            {"name": "Cans(CAN)"},
            {"name": "Cap(CAP)"},
            {"name": "Capsules(CPS)"},
            {"name": "Carat(CT)"},
            {"name": "Carats(CTS)"},
            {"name": "Card(CARD)"},
            {"name": "Cartons(CTN)"},
            {"name": "Case(CASE)"},
            {"name": "Centimeter(CMS)"},
            {"name": "Cents(CNT)"},
            {"name": "Ch(CHAIN)"},
            {"name": "Choka(CHOKA)"},
            {"name": "Chudi(CHUDI)"},
            {"name": "Coil(COIL)"},
            {"name": "Container(CONT)"},
            {"name": "Copy(COPY)"},
            {"name": "Course(COURSE)"},
            {"name": "Crate(CRT)"},
            {"name": "Cream(CRM)"},
            {"name": "Cubic Centimeter(CCM)"},
            {"name": "Cubic Feet(CUFT)"},
            {"name": "Cubic Feet Per Minute(CFM)"},
            {"name": "Cubic Foot(CFT)"},
            {"name": "Cubic Meter(CBM)"},
            {"name": "Cup(CUP)"},
            {"name": "Cv(CV)"},
            {"name": "Daily(DAILY)"},
            {"name": "Dangler(DANGLER)"},
            {"name": "Days(DAY)"},
            {"name": "Daze(DEZ)"},
            {"name": "Dozen(DOZ)"},
            {"name": "Drop(DROP)"},
            {"name": "Drum(DRM)"},
            {"name": "Ea(EA)"},
            {"name": "Each(EACH)"},
            {"name": "Feet(FT)"},
            {"name": "Feet Square(FT2)"},
            {"name": "Fit(FIT)"},
            {"name": "Fold(FLD)"},
            {"name": "Free(FREE)"},
            {"name": "Fts(FTS)"},
            {"name": "Gel(GEL)"},
            {"name": "Glasses(GLS)"},
            {"name": "Grams(GMS)"},
            {"name": "Great Gross(GGR)"},
            {"name": "Gross(GRS)"},
            {"name": "Gross Yards(GYD)"},
            {"name": "Half(HF)"},
            {"name": "Hanger(HEGAR)"},
            {"name": "Hectare(HA)"},
            {"name": "Helmet(HMT)"},
            {"name": "Hours(HRS)"},
            {"name": "Ijn(INJECTION)"},
            {"name": "Inches(IN)"},
            {"name": "Inj(INJECTION)"},
            {"name": "Insertion(INS)"},
            {"name": "Item Id(ITEM ID)"},
            {"name": "Jars(JAR)"},
            {"name": "Jhal(JL)"},
            {"name": "Jhola(JO)"},
            {"name": "Jhola Jhal(JHL)"},
            {"name": "Job(JOB)"},
            {"name": "Katta(KT)"},
            {"name": "Kilograms(KGS)"},
            {"name": "Kiloliter(KLR)"},
            {"name": "Kilometre(KME)"},
            {"name": "Kilovolt-amp(KVA)"},
            {"name": "Kilowatt(KW)"},
            {"name": "Kit(KIT)"},
            {"name": "Ladi(LAD)"},
            {"name": "Length(LENG)"},
            {"name": "Libra Pondo(LBS)"},
            {"name": "Litre(LTR)"},
            {"name": "Lot(LOT)"},
            {"name": "Lump Sum(LS)"},
            {"name": "Man-days(MAN-DAY)"},
            {"name": "Mark(MRK)"},
            {"name": "Mbps(MBPS)"},
            {"name": "Meters(MTR)"},
            {"name": "Metric Million British Thermal Unit(MMBTU)"},
            {"name": "Metric Ton(MTON)"},
            {"name": "Microgram(ΜG)"},
            {"name": "Millicoulomb(M/C)"},
            {"name": "Milligram(MLG)"},
            {"name": "Millilitre(MLT)"},
            {"name": "Millimeter(MM)"},
            {"name": "Minutes(MINS)"},
            {"name": "Month (UOM)"},
            {"name": "Mora(MORA)"},
            {"name": "Nights(NIGHT)"},
            {"name": "None(NONE)"},
            {"name": "Numbers(NOS)"},
            {"name": "Ointment(OINT)"},
            {"name": "Others(OTH)"},
            {"name": "Outer(OR)"},
            {"name": "Package(PKG)"},
            {"name": "Packets(PKT)"},
            {"name": "Pair(PAIR)"},
            {"name": "Pallets(PLT)"},
            {"name": "Pieces(PCS)"},
            {"name": "Pints(PINT)"},
            {"name": "Quintal(QTL)"},
            {"name": "Reel(REEL)"},
            {"name": "Roll(ROLL)"},
            {"name": "Set(SET)"},
            {"name": "Sheets(SHT)"},
            {"name": "Strip(STRIP)"},
            {"name": "Tablets(TABS)"},
            {"name": "Tons(TON)"},
            {"name": "Tubes(TUBE)"},
            {"name": "Units(UNIT)"},
            {"name": "Vial(VIAL)"},
            {"name": "Week(WEEK)"},
            {"name": "Year(YEAR)"}
        ]

        created_count = 0
        for data in default_measuring_units:
            obj, created = MeasuringUnit.objects.get_or_create(name=data["name"])
            if created:
                created_count += 1

        self.stdout.write(self.style.SUCCESS(f"✅ Seeded {created_count} new measuring unit entries globally."))
