# Generated by Django 5.1.6 on 2025-05-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatedInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automated_invoice_no', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('repeat_every', models.PositiveIntegerField(default=1)),
                ('repeat_unit', models.CharField(choices=[('Days', 'Days'), ('Weeks', 'Weeks'), ('Months', 'Months'), ('Yearly', 'Yearly')], default='Weeks', max_length=10)),
                ('payment_terms', models.PositiveIntegerField(default=30)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('apply_tcs', models.BooleanField(default=False)),
                ('tcs_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tcs_on', models.CharField(choices=[('taxable', 'Taxable Amount'), ('total', 'Total Amount')], default='Total Amount', help_text='Apply TCS on either taxable or total amount', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total Amount', max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='static/images/')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Paused', 'Paused'), ('Stopped', 'Stopped')], default='Active', max_length=10)),
            ],
        ),
    ]
