# Generated by Django 5.1.6 on 2025-05-05 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automated_bills', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatedInvoiceExtension',
            fields=[
                ('invoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales.invoice')),
                ('invoice_data', models.JSONField()),
            ],
            options={
                'verbose_name': 'Automated Invoice Extension',
                'verbose_name_plural': 'Automated Invoice Extensions',
            },
            bases=('sales.invoice',),
        ),
        migrations.CreateModel(
            name='AutomatedInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('hsn_code', models.CharField(blank=True, max_length=20, null=True)),
                ('price_item', models.DecimalField(blank=True, decimal_places=2, help_text='Unit price in ₹', max_digits=10, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
