# Generated by Django 5.1.6 on 2025-05-05 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('godown', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='godown',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='godowns', to='users.business'),
        ),
        migrations.AddField(
            model_name='godown',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='godowns', to='godown.state'),
        ),
        migrations.AlterUniqueTogether(
            name='godown',
            unique_together={('business', 'godownName')},
        ),
    ]
