# Generated by Django 5.1.6 on 2025-05-05 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cash_and_bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='Discount in percentage.', max_digits=5)),
                ('price_item', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card', 'Card'), ('Netbanking', 'Netbanking'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque')], max_length=100)),
                ('payment_out_number', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['payment_out_number'],
            },
        ),
        migrations.CreateModel(
            name='PaymentOutPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('settled_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_no', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Partially Paid', 'Partially Paid'), ('Paid', 'Paid')], default='Unpaid', max_length=20)),
                ('payment_term', models.PositiveIntegerField(blank=True, default=30, help_text='Number of days for the payment term', null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('original_invoice_no', models.CharField(blank=True, max_length=50, null=True)),
                ('is_fully_paid', models.BooleanField(default=False, help_text='Mark as fully paid')),
                ('amount_received', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount received', max_digits=10)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Balance Amount', max_digits=10)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Taxable Amount', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total Amount', max_digits=10)),
                ('total_payable_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total Payable Amount', max_digits=10)),
                ('apply_tcs', models.BooleanField(default=False)),
                ('tcs_on', models.CharField(choices=[('taxable', 'taxable'), ('total', 'total')], default='total', help_text='Apply TCS on either taxable or total amount', max_length=20)),
                ('tcs_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='TCS Amount', max_digits=10)),
                ('apply_tds', models.BooleanField(default=False)),
                ('tds_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card', 'Card'), ('Netbanking', 'Netbanking'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque')], default='Cash', max_length=20, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Discount in percentage.', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='static/images/')),
            ],
            options={
                'ordering': ['purchase_no'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='Discount in percentage.', max_digits=5)),
                ('price_item', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_updated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order_no', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=10)),
                ('payment_term', models.PositiveIntegerField(blank=True, default=30, null=True)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Balance Amount', max_digits=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total Amount', max_digits=10)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Discount in percentage.', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='static/signature/')),
            ],
            options={
                'ordering': ['purchase_order_no'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('price_item', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='Discount in percentage.', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchasereturn_no', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Partially Paid', 'Partially Paid'), ('Paid', 'Paid')], default='Unpaid', max_length=20)),
                ('is_fully_paid', models.BooleanField(default=False, help_text='Mark as fully paid')),
                ('amount_received', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount received', max_digits=10)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Balance Amount', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total Amount', max_digits=10)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Taxable Amount', max_digits=10)),
                ('payment_method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card', 'Card'), ('Netbanking', 'Netbanking'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque')], default='Cash', max_length=20, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Discount in percentage.', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='static/images/')),
                ('purchase_id', models.PositiveIntegerField()),
                ('purchase_no', models.PositiveIntegerField(blank=True, null=True)),
                ('total_payable_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total Payable Amount', max_digits=10)),
                ('apply_tcs', models.BooleanField(default=False)),
                ('tcs_on', models.CharField(choices=[('taxable', 'taxable'), ('total', 'total')], default='total', help_text='Apply TCS on either taxable or total amount', max_length=20)),
                ('tcs_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='TCS Amount', max_digits=10)),
                ('apply_tds', models.BooleanField(default=False)),
                ('tds_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'ordering': ['purchasereturn_no'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='Discount in percentage.', max_digits=5)),
                ('price_item', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DebitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debitnote_no', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Partially Paid', 'Partially Paid'), ('Paid', 'Paid')], default='Unpaid', max_length=20)),
                ('is_fully_paid', models.BooleanField(default=False, help_text='Mark as fully paid')),
                ('amount_received', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount received', max_digits=10)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Balance Amount', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total Amount', max_digits=10)),
                ('payment_method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card', 'Card'), ('Netbanking', 'Netbanking'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque')], default='Cash', max_length=20, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Discount in percentage.', max_digits=5, null=True)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Taxable Amount', max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='static/images/')),
                ('purchasereturn_id', models.PositiveIntegerField()),
                ('purchasereturn_no', models.PositiveIntegerField(blank=True, null=True)),
                ('total_payable_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total Payable Amount', max_digits=10)),
                ('apply_tcs', models.BooleanField(default=False)),
                ('tcs_on', models.CharField(choices=[('taxable', 'taxable'), ('total', 'total')], default='total', help_text='Apply TCS on either taxable or total amount', max_length=20)),
                ('tcs_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='TCS Amount', max_digits=10)),
                ('apply_tds', models.BooleanField(default=False)),
                ('tds_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debitnote', to='cash_and_bank.bankaccount')),
            ],
            options={
                'ordering': ['debitnote_no'],
            },
        ),
    ]
