# Generated by Django 5.1.6 on 2025-05-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Submitted', 'Submitted'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('irn', models.CharField(blank=True, help_text='Invoice Reference Number from GST portal', max_length=100, null=True, unique=True)),
                ('raw_invoice', models.JSONField(blank=True, help_text='Generated JSON before NIC response', null=True)),
                ('ack_no', models.CharField(blank=True, help_text='Acknowledgement Number from portal', max_length=50, null=True)),
                ('ack_date', models.DateTimeField(blank=True, help_text='Acknowledgement DateTime', null=True)),
                ('signed_invoice', models.TextField(blank=True, help_text='Signed e-invoice JSON or base64 content', null=True)),
                ('signed_qr_code', models.TextField(blank=True, help_text='Base64 encoded QR code', null=True)),
                ('qr_code_image', models.ImageField(blank=True, help_text='QR code image', null=True, upload_to='qr_codes/')),
                ('invoice_type', models.CharField(choices=[('B2B', 'B2B'), ('B2C', 'B2C'), ('EXP', 'Export')], default='B2B', max_length=20)),
                ('supply_type', models.CharField(choices=[('Inter', 'Inter State'), ('Intra', 'Intra State')], default='Inter', max_length=20)),
                ('document_type', models.CharField(choices=[('INV', 'Invoice'), ('CRN', 'Credit Note'), ('DBN', 'Debit Note')], default='INV', max_length=20)),
                ('seller_gstin', models.CharField(max_length=15)),
                ('buyer_gstin', models.CharField(max_length=15)),
                ('error_message', models.TextField(blank=True, help_text='Error or response from e-invoice API', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EWayBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Generated', 'Generated'), ('Cancelled', 'Cancelled'), ('Expired', 'Expired'), ('Updated', 'Updated')], default='Generated', max_length=30)),
                ('irn', models.CharField(max_length=64, unique=True)),
                ('trans_id', models.CharField(max_length=15)),
                ('trans_name', models.CharField(max_length=100)),
                ('trans_mode', models.CharField(choices=[('1', 'Road'), ('2', 'Rail'), ('3', 'Air'), ('4', 'Ship')], default='1', max_length=1)),
                ('distance', models.PositiveIntegerField(default=1, help_text='Distance between source and destination PIN codes')),
                ('trans_doc_no', models.CharField(max_length=15)),
                ('trans_doc_dt', models.CharField(max_length=10)),
                ('veh_no', models.CharField(max_length=20)),
                ('veh_type', models.CharField(choices=[('O', 'ODC'), ('R', 'Regular')], max_length=1)),
                ('exp_ship_addr1', models.CharField(max_length=100)),
                ('exp_ship_addr2', models.CharField(blank=True, max_length=100, null=True)),
                ('exp_ship_loc', models.CharField(max_length=100)),
                ('exp_ship_pin', models.PositiveIntegerField()),
                ('exp_ship_stcd', models.CharField(max_length=2)),
                ('disp_name', models.CharField(max_length=100)),
                ('disp_addr1', models.CharField(max_length=100)),
                ('disp_addr2', models.CharField(blank=True, max_length=100, null=True)),
                ('disp_loc', models.CharField(max_length=100)),
                ('disp_pin', models.PositiveIntegerField()),
                ('disp_stcd', models.CharField(max_length=2)),
                ('generated_date', models.DateTimeField(blank=True, null=True)),
                ('valid_upto', models.DateTimeField(blank=True, null=True)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancel_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GSTR1Reconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_invoice_no', models.CharField(blank=True, help_text='Invoice number from GST portal', max_length=100, null=True)),
                ('gst_invoice_date', models.DateField(blank=True, help_text='Invoice date from GST portal', null=True)),
                ('gst_invoice_value', models.DecimalField(blank=True, decimal_places=2, help_text='Invoice value from GST portal', max_digits=12, null=True)),
                ('gst_gstin', models.CharField(blank=True, help_text='GSTIN of the buyer from GST portal', max_length=15, null=True)),
                ('local_invoice_value', models.DecimalField(blank=True, decimal_places=2, help_text='Invoice value from system', max_digits=12, null=True)),
                ('local_gstin', models.CharField(blank=True, help_text='GSTIN of the buyer from system', max_length=15, null=True)),
                ('status', models.CharField(choices=[('Matched', 'Matched'), ('Mismatched', 'Mismatched'), ('Missing in Portal', 'Missing in Portal'), ('Missing in System', 'Missing in System')], default='Matched', max_length=50)),
                ('remarks', models.TextField(blank=True, help_text='Any notes or reasons for mismatch', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
