# Generated by Django 5.1.6 on 2025-05-05 09:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cash_and_bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='Discount in percentage.', max_digits=5)),
                ('price_item', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_challan_no', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=10)),
                ('payment_term', models.PositiveIntegerField(blank=True, default=30, null=True)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Balance Amount', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total Amount', max_digits=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Discount in percentage.', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='static/signature/')),
            ],
            options={
                'ordering': ['delivery_challan_no'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryChallanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_item', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='Discount in percentage.', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Partially Paid', 'Partially Paid'), ('Paid', 'Paid')], default='Unpaid', max_length=20)),
                ('payment_term', models.PositiveIntegerField(blank=True, default=30, help_text='Number of days for the payment term', null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_fully_paid', models.BooleanField(default=False, help_text='Mark as fully paid')),
                ('amount_received', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount received', max_digits=10)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Balance Amount', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total Amount', max_digits=10)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Taxable Amount', max_digits=10)),
                ('payment_method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card', 'Card'), ('Netbanking', 'Netbanking'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque')], default='Cash', max_length=20, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Discount in percentage.', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='static/images/')),
                ('apply_tcs', models.BooleanField(default=False)),
                ('tcs_on', models.CharField(choices=[('taxable', 'taxable'), ('total', 'total')], default='total', help_text='Apply TCS on either taxable or total amount', max_length=20)),
                ('tcs_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='TCS Amount', max_digits=10)),
            ],
            options={
                'ordering': ['invoice_no'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='Discount in percentage.', max_digits=5)),
                ('price_item', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card', 'Card'), ('Netbanking', 'Netbanking'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque')], max_length=100)),
                ('payment_in_number', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['payment_in_number'],
            },
        ),
        migrations.CreateModel(
            name='PaymentInInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('settled_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('apply_tds', models.BooleanField(default=False)),
                ('tds_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tds_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proforma_no', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=10)),
                ('payment_term', models.PositiveIntegerField(default=30, help_text='Number of days for the payment term')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Balance Amount', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total Amount', max_digits=10)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Discount in percentage.', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='static/signature/')),
            ],
            options={
                'ordering': ['proforma_no'],
            },
        ),
        migrations.CreateModel(
            name='ProformaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_item', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='Discount in percentage.', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_no', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=10)),
                ('payment_term', models.PositiveIntegerField(default=30, help_text='Number of days for the payment term')),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Balance Amount', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total Amount', max_digits=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Discount in percentage.', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='static/signature/')),
            ],
            options={
                'ordering': ['quotation_no'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='Discount in percentage.', max_digits=5)),
                ('price_item', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesreturn_no', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Partially Paid', 'Partially Paid'), ('Paid', 'Paid')], default='Unpaid', max_length=20)),
                ('is_fully_paid', models.BooleanField(default=False, help_text='Mark as fully paid')),
                ('amount_received', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount received', max_digits=10)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Balance Amount', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total Amount', max_digits=10)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Taxable Amount', max_digits=10)),
                ('payment_method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card', 'Card'), ('Netbanking', 'Netbanking'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque')], default='Cash', max_length=20, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Discount in percentage.', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='static/images/')),
                ('invoice_id', models.PositiveIntegerField()),
                ('invoice_no', models.PositiveIntegerField(blank=True, null=True)),
                ('apply_tcs', models.BooleanField(default=False)),
                ('tcs_on', models.CharField(choices=[('taxable', 'taxable'), ('total', 'total')], default='total', help_text='Apply TCS on either taxable or total amount', max_length=20)),
                ('tcs_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='TCS Amount', max_digits=10)),
            ],
            options={
                'ordering': ['salesreturn_no'],
            },
        ),
        migrations.CreateModel(
            name='SalesReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='Discount in percentage.', max_digits=5)),
                ('price_item', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tcs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('section', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('condition', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('section', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_note_no', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Partially Paid', 'Partially Paid'), ('Paid', 'Paid')], default='Unpaid', max_length=20)),
                ('is_fully_paid', models.BooleanField(default=False, help_text='Mark as fully paid')),
                ('amount_received', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount received', max_digits=10)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Balance Amount', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total Amount', max_digits=10)),
                ('payment_method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card', 'Card'), ('Netbanking', 'Netbanking'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque')], default='Cash', max_length=20, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Discount in percentage.', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='static/images/')),
                ('salesreturn_id', models.PositiveIntegerField()),
                ('salesreturn_no', models.PositiveIntegerField(blank=True, null=True)),
                ('apply_tcs', models.BooleanField(default=False)),
                ('tcs_on', models.CharField(choices=[('taxable', 'taxable'), ('total', 'total')], default='total', help_text='Apply TCS on either taxable or total amount', max_length=20)),
                ('tcs_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='TCS Amount', max_digits=10)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Taxable Amount', max_digits=10)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creditnote', to='cash_and_bank.bankaccount')),
            ],
            options={
                'ordering': ['credit_note_no'],
            },
        ),
    ]
