# Generated by Django 5.1.6 on 2025-05-05 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cash_and_bank', '0002_initial'),
        ('inventory', '0002_initial'),
        ('parties', '0002_initial'),
        ('sales', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditnote', to='users.business'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties.party'),
        ),
        migrations.AddField(
            model_name='creditnoteitem',
            name='creditnote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditnote_items', to='sales.creditnote'),
        ),
        migrations.AddField(
            model_name='creditnoteitem',
            name='gstTaxRate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.gsttaxrate'),
        ),
        migrations.AddField(
            model_name='creditnoteitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
        migrations.AddField(
            model_name='creditnoteitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.service'),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverychallan', to='users.business'),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties.party'),
        ),
        migrations.AddField(
            model_name='deliverychallanitem',
            name='deliverychallan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverychallan_items', to='sales.deliverychallan'),
        ),
        migrations.AddField(
            model_name='deliverychallanitem',
            name='gstTaxRate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.gsttaxrate'),
        ),
        migrations.AddField(
            model_name='deliverychallanitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
        migrations.AddField(
            model_name='deliverychallanitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.service'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='cash_and_bank.bankaccount'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='users.business'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties.party'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='gstTaxRate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.gsttaxrate'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='sales.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.service'),
        ),
        migrations.AddField(
            model_name='paymentin',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_ins', to='cash_and_bank.bankaccount'),
        ),
        migrations.AddField(
            model_name='paymentin',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentin', to='users.business'),
        ),
        migrations.AddField(
            model_name='paymentin',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties.party'),
        ),
        migrations.AddField(
            model_name='paymentininvoice',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.invoice'),
        ),
        migrations.AddField(
            model_name='paymentininvoice',
            name='payment_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.paymentin'),
        ),
        migrations.AddField(
            model_name='paymentin',
            name='settled_invoices',
            field=models.ManyToManyField(blank=True, related_name='payments_settled', through='sales.PaymentInInvoice', to='sales.invoice'),
        ),
        migrations.AddField(
            model_name='proforma',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proforma', to='users.business'),
        ),
        migrations.AddField(
            model_name='proforma',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties.party'),
        ),
        migrations.AddField(
            model_name='proformaitem',
            name='gstTaxRate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.gsttaxrate'),
        ),
        migrations.AddField(
            model_name='proformaitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
        migrations.AddField(
            model_name='proformaitem',
            name='proforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proforma_items', to='sales.proforma'),
        ),
        migrations.AddField(
            model_name='proformaitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.service'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation', to='users.business'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties.party'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='gstTaxRate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.gsttaxrate'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_items', to='sales.quotation'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.service'),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salesreturn', to='cash_and_bank.bankaccount'),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesreturn', to='users.business'),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties.party'),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='gstTaxRate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.gsttaxrate'),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='salesreturn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesreturn_items', to='sales.salesreturn'),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.service'),
        ),
        migrations.AddField(
            model_name='tcs',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tcs_rates', to='users.business'),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='tcs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salesreturn_tcs', to='sales.tcs'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tcs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_tcs', to='sales.tcs'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='tcs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creditnote_tcs', to='sales.tcs'),
        ),
        migrations.AddField(
            model_name='tds',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tds_rates', to='users.business'),
        ),
        migrations.AlterUniqueTogether(
            name='deliverychallan',
            unique_together={('business', 'delivery_challan_no')},
        ),
        migrations.AlterUniqueTogether(
            name='paymentin',
            unique_together={('business', 'payment_in_number')},
        ),
        migrations.AlterUniqueTogether(
            name='proforma',
            unique_together={('business', 'proforma_no')},
        ),
        migrations.AlterUniqueTogether(
            name='quotation',
            unique_together={('business', 'quotation_no')},
        ),
        migrations.AlterUniqueTogether(
            name='tcs',
            unique_together={('business', 'rate', 'section', 'description')},
        ),
        migrations.AlterUniqueTogether(
            name='salesreturn',
            unique_together={('business', 'salesreturn_no')},
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('business', 'invoice_no')},
        ),
        migrations.AlterUniqueTogether(
            name='creditnote',
            unique_together={('business', 'credit_note_no')},
        ),
        migrations.AlterUniqueTogether(
            name='tds',
            unique_together={('business', 'rate', 'section', 'description')},
        ),
    ]
